### ISSUE TITLE
No Module named control

### ISSUE THREAD

**Issue by mzahana** [dronecrew/px4tools#10]
Hi, 

I am trying to run the automatic sysid and control example. When I execute the first block

``` python
%load_ext autoreload
%autoreload 2c
import px4tools
import px4tools.logsysid
import pandas
import control
import json
%pylab inline
```

I get the following error:

```
/home/abdkadma/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-eb5f1f38bc91> in <module>()
      2 get_ipython().magic(u'autoreload 2c')
      3 import px4tools
----> 4 import px4tools.logsysid
      5 import pandas
      6 import control

/home/abdkadma/anaconda2/lib/python2.7/site-packages/px4tools/logsysid.py in <module>()
      6 
      7 import pandas
----> 8 import control
      9 import scipy.optimize
     10 import scipy.signal

ImportError: No module named control
```

What could be the issue?

**Comment by mzahana** [comment]
@jgoppert any clue?

**Comment by jgoppert** [comment]
@mzahana This module requires the python control library:

https://github.com/python-control/python-control

**Comment by mzahana** [comment]
The control module problem is solved. Another issue arise, but will open a new issue for that.

**Comment by rjvaroky-ctrl** [comment]
After running python mission_test.py MC_mission_box.plan, File "mission_test.py
FOllwoing error was obtained
", line 50, in <module> from px4tools import ulog
ModuleNotFoundError: No module named 'px4tools'

Please help, how to solve this error, I am new to it and dont know how to rectify it

**Comment by rjvaroky-ctrl** [comment]
@jgoppert any clue?

**Comment by mzahana** [comment]
@rjvaroky-ctrl you need to install the px4tools module.

**Comment by rjvaroky-ctrl** [comment]
@jgoppert Can u give code for ubuntu 20.04 to install px4tools module sudo apt-get install px4tools module is not working

**Comment by A1A1G2** [comment]
> @jgoppert Can u give code for ubuntu 20.04 to install px4tools module sudo apt-get install px4tools module is not working
you can use :
pip install px4tools

**Comment by Smark2019** [comment]
Hi for all,
I have also an issue during importing the px4tools.
My ubuntu: 18.04 and pip install is not working. What I get during "pip install px4tools":


DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting px4tools==0.9.4
  Downloading px4tools-0.9.4.tar.gz (42 kB)
     |████████████████████████████████| 42 kB 268 kB/s 
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from px4tools==0.9.4) (1.13.3)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python2.7/dist-packages (from px4tools==0.9.4) (0.24.2)
Collecting pyulog
  Using cached pyulog-0.9.0.tar.gz (38 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-AbG1go/pyulog/setup.py'"'"'; __file__='"'"'/tmp/pip-install-AbG1go/pyulog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-DhEy_8
         cwd: /tmp/pip-install-AbG1go/pyulog/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-AbG1go/pyulog/setup.py", line 14, in <module>
        import versioneer
      File "versioneer.py", line 1739
        file=sys.stderr)
            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



Is there anyone who faced it before?

**Comment by jgoppert** [comment]
I would try: https://github.com/dronecrew/ulog_tools. That is a rework of px4tools and I think it is python3 compliant.
